[package]
name = "spring"
description = "Rust microservice framework like spring boot in java"
version = "0.2.5"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
inline_file = []

[dependencies]
spring-macros = { path = "../spring-macros", version = "0.2.0" }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "json",
    "env-filter",
    "tracing-log",
    "chrono",
] }
inventory = { workspace = true }
dotenvy = { workspace = true }
toml = { workspace = true, features = ["parse"] }
serde-toml-merge = { workspace = true }
async-trait = { workspace = true }
schemars = { workspace = true }
tokio = { workspace = true, features = ["full"] }
dashmap = { workspace = true }
rust-embed = { version = "8.5.0", features = ["interpolate-folder-path", "debug-embed"] }

[dev-dependencies]
tempfile = "3.12"
spring-sqlx = { path = "../spring-sqlx" }
spring-web = { path = "../spring-web" }
spring-job = { path = "../spring-job" }
spring-stream = { path = "../spring-stream" }
